// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaF-AlWZ5Uc0iK4iZhQ-rmlrBMb1xUWFY',
    appId: '1:538478411887:web:87690b179b096764cd4d9a',
    messagingSenderId: '538478411887',
    projectId: 'pvt-notes',
    authDomain: 'pvt-notes.firebaseapp.com',
    storageBucket: 'pvt-notes.firebasestorage.app',
    measurementId: 'G-J960CHDCWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb21XOaK4L54AS4rmCgcGhCXyHUJG_wSk',
    appId: '1:538478411887:android:036b8fae9ae0dec4cd4d9a',
    messagingSenderId: '538478411887',
    projectId: 'pvt-notes',
    storageBucket: 'pvt-notes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmlRq1SGY2x8zJF2QEgTvCBWQhM-enKzU',
    appId: '1:538478411887:ios:e1389c34def0cfbbcd4d9a',
    messagingSenderId: '538478411887',
    projectId: 'pvt-notes',
    storageBucket: 'pvt-notes.firebasestorage.app',
    iosBundleId: 'com.learningstuff.pvtnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmlRq1SGY2x8zJF2QEgTvCBWQhM-enKzU',
    appId: '1:538478411887:ios:e1389c34def0cfbbcd4d9a',
    messagingSenderId: '538478411887',
    projectId: 'pvt-notes',
    storageBucket: 'pvt-notes.firebasestorage.app',
    iosBundleId: 'com.learningstuff.pvtnotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaF-AlWZ5Uc0iK4iZhQ-rmlrBMb1xUWFY',
    appId: '1:538478411887:web:96ad6b53d00dd89fcd4d9a',
    messagingSenderId: '538478411887',
    projectId: 'pvt-notes',
    authDomain: 'pvt-notes.firebaseapp.com',
    storageBucket: 'pvt-notes.firebasestorage.app',
    measurementId: 'G-LD4X1GVN9X',
  );
}
